"""
Fisheye distortion utilities for Google Immersive datasets.

For Immersive fisheye cameras, the renderer produces images at 2× resolution in undistorted space.
These are then warped back to the original fisheye (distorted) space using precomputed
distortion flow maps, and compared against the raw distorted ground truth images.
This avoids undistortion artifacts (black borders, interpolation errors).
"""

import os
import numpy as np
import torch
import torch.nn.functional as F


def getfisheyemapper(dataset_root, camera_name):
    """
    Load the precomputed fisheye distortion flow map for a camera.
    
    The .npy files are generated by preprocessing/colmap_from_video_immersive.py's getdistortedflow()
    for frame 0 of each camera. They contain a grid of normalized coordinates [-1, 1]
    that map each pixel in the distorted image to its corresponding location in the
    undistorted image — suitable for use with F.grid_sample.
    
    Args:
        dataset_root: Root path of the immersive dataset (e.g., data/google_immersive/02_Flames_dist)
        camera_name: Camera name without extension (e.g., "camera_0001")
    
    Returns:
        Tensor of shape [1, H, W, 2] on CPU, dtype float32
        (moved to GPU on-the-fly during apply_distortion_warp to avoid OOM)
    """
    flow_path = os.path.join(dataset_root, camera_name + ".npy")
    if not os.path.exists(flow_path):
        raise FileNotFoundError(
            f"Distortion flow map not found: {flow_path}\n"
            f"Run preprocessing/colmap_from_video_immersive.py first to generate .npy flow maps."
        )
    flow = np.load(flow_path)
    flow = torch.from_numpy(flow).unsqueeze(0).float()  # stay on CPU
    return flow


def apply_distortion_warp(rendered_2x, fisheyemapper, gt_height, gt_width):
    """
    Warp a 2×-resolution rendered image through the fisheye distortion flow map.
    
    The flow map is at the original (distorted) image resolution. When used with
    grid_sample on the 2× rendered image, it produces the distorted version at the
    flow map's spatial resolution. If the flow map resolution doesn't match the GT
    resolution, the result is resized to match.
    
    Args:
        rendered_2x: Rendered image at 2× resolution, shape [C, 2*H, 2*W]
        fisheyemapper: Distortion flow tensor, shape [1, H_flow, W_flow, 2]
        gt_height: Target GT height
        gt_width: Target GT width
    
    Returns:
        Warped image at GT resolution, shape [C, gt_height, gt_width]
    """
    # Add batch dimension: [1, C, 2H, 2W]
    rendered_batch = rendered_2x.unsqueeze(0)
    
    # Move flow map to same device as rendered image (lazy GPU transfer)
    if fisheyemapper.device != rendered_2x.device:
        fisheyemapper = fisheyemapper.to(rendered_2x.device)
    
    # Resize flow map to match GT resolution if needed
    flow_h, flow_w = fisheyemapper.shape[1], fisheyemapper.shape[2]
    if flow_h != gt_height or flow_w != gt_width:
        # Flow values are in [-1, 1] (normalized), so bilinear interpolation is valid
        # Reshape to [1, 2, H, W] for interpolation, then back to [1, H', W', 2]
        flow_resized = fisheyemapper.permute(0, 3, 1, 2)  # [1, 2, H_flow, W_flow]
        flow_resized = F.interpolate(flow_resized, size=(gt_height, gt_width), mode='bilinear', align_corners=True)
        flow_resized = flow_resized.permute(0, 2, 3, 1)  # [1, gt_height, gt_width, 2]
    else:
        flow_resized = fisheyemapper
    
    # grid_sample: sample the 2× rendered image at distorted coordinates
    # Output shape: [1, C, gt_height, gt_width]
    warped = F.grid_sample(rendered_batch, flow_resized, mode='bilinear', 
                           padding_mode='zeros', align_corners=True)
    
    return warped.squeeze(0)  # [C, gt_height, gt_width]
